Chore/husky and commitlint
nicklima-amigos/pro-vaxina pull request #6
Opened 2024-03-26 17:43 UTC by ograndlucius

Added the husky and commitlint packages.

2024-03-26 17:48 UTC, alss03 approved these changes
Looks good to me.

2024-03-26 17:50 UTC, raphael-foliveira requested changes

2024-03-26 17:50 UTC, raphael-foliveira commented on api/package.json
> +    },
Os hooks não estão rodando ao commitar. 
Acredito que esses scripts devem estar em bash dentro da pasta .husky

2024-03-27 13:50 UTC, raphael-foliveira commented on web/tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "../api/commitlint.config copy.ts"],
Corrigir o nome do último include.
Acredito que seja 
`"../api/commitlint.config.ts"`

2024-03-27 13:51 UTC, raphael-foliveira commented on web/tsconfig.json
> +  "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx", ".next/types/**/*.ts", "../api/commitlint.config copy.ts"],
Esse arquivo está no projeto da api. Ele provavelmente não deve estar aqui na config do frontend, não?

2024-03-28 02:05 UTC, raphael-foliveira commented
Modificações mergeadas em https://github.com/nicklima-amigos/pro-vaxina/pull/12

2024-03-28 02:05 UTC, closed without merging